### ISSUE TITLE
Remove xconsole output action

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-pkg-ubuntu#1]
Almost nobody uses that functionality, yet rsyslog always is configured to write to that pipe. This causes performance loss. Also, users are often confused what this is all about (judging from mailing list and forum posts). An unintrusive solution probably is to simply comment out the statement and add a comment when it should be activated.

**Comment by almafaa** [comment]
شكرآ لمساهمتك مرحبا ألمانيا

**Comment by almafaa** [comment]
الكل يتابع ويساهم ياااااالرررروعة

**Comment by almafaa** [comment]
الكل يتابع ويساهم ياااااالرررروعة
