### ISSUE TITLE
No Ubuntu 14.10 Utopic rsyslog packages

### ISSUE THREAD

**Issue by zasran** [rsyslog/rsyslog-pkg-ubuntu#13]
Can you please create rsyslog package for Ubuntu 14.10 Utopic? Thanks!

**Comment by rgerhards** [comment]
At least we have them now for the daily builds:
http://www.rsyslog.com/downloads/download-daily-build/

Hope to have time to work on the regular builds in the next time.

**Comment by rgerhards** [comment]
For v8-stables, this is currently being implemented. Will be available tomorrow.
