### ISSUE TITLE
ubuntu-noble packages

### ISSUE THREAD

**Issue by ramonskie** [rsyslog/rsyslog-pkg-ubuntu#168]
are there any plans to also build rsyslog for noble?
as we are in need of `rsyslog-mmjsonparse` `rsyslog-mmnormaliz` for noble

**Comment by fukawi2** [comment]
We are also keen for packages to be available for 24.04 🙏

**Comment by fukawi2** [comment]
Thanks @alorbach - appreciate your efforts :)
