### ISSUE TITLE
How to fetch sources

### ISSUE THREAD

**Issue by xrl** [rsyslog/rsyslog-pkg-ubuntu#17]
How can I perform a git checkout and generate a source tar file suitable for building with these scripts?

**Comment by rgerhards** [comment]
1. Checkout rsyslog git
2. Autoreconf   -vfi
3. ./configure
4. Make dist

Sent from phone, thus brief.
Am 09.04.2015 23:08 schrieb "Xavier Lange" <notifications@github.com>:

**Comment by xrl** [comment]
Ah, I assumed building the source dist was automated. Thanks!


—

**Comment by rgerhards** [comment]
Just for the records, the fetch process is now part of the rsyslog-infrastructure project.
