### ISSUE TITLE
Debug symbol packages for Ubuntu stable build

### ISSUE THREAD

**Issue by hakman** [rsyslog/rsyslog-pkg-ubuntu#21]
Some days ago we got into this [issue] (https://github.com/rsyslog/rsyslog/commit/0181d341b7b875f05436f6a15205c7eb291ba141) and Rsyslog kept crashing.
We tried to find the root cause, but core files were not very useful because the debug symbols were missing. In the end, we compiled Rsyslog locally and traced the crashes to this issue.

Could we have debug symbol package(s) for Rsylog and plugins for Ubuntu & Debian stable builds?
I see that the RHEL/CentOS repo has such packages but could not find for Ubuntu.

Thanks in advance.

**Comment by rgerhards** [comment]
done today
