### ISSUE TITLE
Rsyslog daily builds missing rsyslog-mmutf8fix

### ISSUE THREAD

**Issue by hakman** [rsyslog/rsyslog-pkg-ubuntu#22]
I am using Rsyslog daily build to avoid an issue that was introduced in latest stable, but fixed since.
I hoped that I could only changed the repo to devel and upgrade, but gut into an issue with missing     rsyslog-mmutf8fix.

Looking at the [repo](http://ppa.launchpad.net/adiscon/v8-devel/ubuntu/pool/main/r/rsyslog/), I see that rsyslog-mmutf8fix wasn't built for 8.10. The latest version is 8.7. There are also other packages with version 8.7, that should be removed.

Maybe it would be a good idea to check the upgrade to the daily build and fix missing packages and also remove old packages before pushing a new build.

Thanks in advance.

**Comment by ealphonse** [comment]
Hello,

rsyslog-mmutf8fix in [v8-stable](http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/pool/main/r/rsyslog/) and [v8-devel](http://ppa.launchpad.net/adiscon/v8-devel/ubuntu/pool/main/r/rsyslog/) is no longer built for ubuntu versions newer than trusty.

Is it a deprecated module?

Thanks in advance,

Erick

**Comment by ealphonse** [comment]
Hello, as `8.25` is out, I checked [v8-stable](http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/pool/main/r/rsyslog/) and [v8-devel](http://ppa.launchpad.net/adiscon/v8-devel/ubuntu/pool/main/r/rsyslog/) and all packages are built for xenial and later ubuntu versions but rsyslog-mmutf8fix.

Does it confirm that it is a deprecated module? Is there a new way to curate the input?

Thank for any input

**Comment by friedl** [comment]
Sorry for the late reply. This was fixed a while ago for stable. The daily build will receive it again in the next iteration.

https://github.com/rsyslog/rsyslog-pkg-ubuntu/commit/654c0131eeb3dece638b3bbe0fa164903891c0aa

**Comment by hakman** [comment]
Great. Thanks! 👍

**Comment by ealphonse** [comment]
Thank you @friedl :-)

**Comment by friedl** [comment]
@alecswan With that version we switched to the original spec file from the CentOS released RPM as template. That also meant some changes to the RPM. mmutf8fix was discontinued as separate RPM and is distributed through the main RPM.

**Comment by alecswan** [comment]
Thanks, @friedl. I was hoping to find such changes documented in https://github.com/rsyslog/rsyslog/blob/v8-stable/ChangeLog unless there is a different place for them. Thanks!

**Comment by friedl** [comment]
@alecswan Changes to the packaging are not shown in the Changelog of the rsyslog project itself. These are only visible in the commit history of the respective packaging project here on Github.

Commit of said changes: https://github.com/rsyslog/rsyslog-pkg-rhel-centos/commit/d510a6b28b5ebd82c9788e9d20ca34b0566c356c

**Comment by rgerhards** [comment]
@friedl I guess (without reading in-depth) what @alecswan means is that this change should show up in the package ChangeLog. If so, I agree that's correct, it should be visible there. Commit log is not for user review.

**Comment by rgerhards** [comment]
oh, I should have looked a bit more closely, he referred to the source project. Yup, that's the wrong place. But we should anyhow make sure that the package ChangeLog contains such info if it does not yet.
