### ISSUE TITLE
imczmq / omczmq plugin packages

### ISSUE THREAD

**Issue by taotetek** [rsyslog/rsyslog-pkg-ubuntu#24]
The imczmq / omczmq (zeromq) plugins depend on stable versions of zeromq and czmq that are not yet packaged for ubuntu.  In order to build rsyslog-omczmq / rsyslog-imczmq plugins we need the following dependencies:
- libsodium (included in ubuntu)
- zeromq stable release 4.1.2 (not included in ubuntu)
- czmq stable release v3.0.2 (not included in ubuntu)

**Comment by rgerhards** [comment]
It looks like newer Ubuntu does have this as rsyslog-czmq; so we can look up their definitions.
