### ISSUE TITLE
package rename requires cleanup of ppa

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-pkg-ubuntu#33]
the package versions have been reneamed to tilde date vs. dot date. This means the dot versions always appear newer, which in turn means the old dot versions prevent upload of new ones. In a nutshell, we do not have any real package updates until we clean out the old cruft.

**Comment by davidelang** [comment]
This should settle out after the next release, 8.19.0~* will be after 8.18.0.*

For packages that are not being bumped to a new version, cleanup or changing the 
old packages may be desirable.

For those who didn't see the changeset making this change. the reason for the 
change is that version numbers get bumped right after the release, so all 
development snapshots have the version number of the next release. With dot as 
the separator, final releases were not replacing the nightly versions. With 
tilde, the final releases replace thedevelopment snapshots.

David Lang

**Comment by rgerhards** [comment]
Completed
