### ISSUE TITLE
mmgrok package

### ISSUE THREAD

**Issue by radu-gheorghe** [rsyslog/rsyslog-pkg-ubuntu#45]
mmgrok readme can be found here: https://github.com/rsyslog/rsyslog/tree/master/contrib/mmgrok

One can find so many grok rules all over the Internet that it sounds very tempting for a lot of use-cases,
especially those with few rules.

**Comment by rgerhards** [comment]
can you provide the necessary package definitions?

**Comment by radu-gheorghe** [comment]
To be honest I don't know how to do that. But when/if I'll have time to look them up I'll come up with a PR.
