### ISSUE TITLE
rsyslog-kafka package not available for ubuntu 16.04

### ISSUE THREAD

**Issue by eli-jordan** [rsyslog/rsyslog-pkg-ubuntu#53]
I have followed the instructions listed here http://www.rsyslog.com/ubuntu-repository/ to install rsyslog with success. However, I want to use the omkafka module, but running `apt-get install rsyslog-kafka` reports that the package is not available.

Are there additional steps I need to install the Kafka output?

I was able to compile from source, install librdkafka and copy the omkafka.so onto the system, and this seems to work, but I would rather use the official packages

**Comment by friedl** [comment]
This issue should be solved. In the meantime, we changed how the Kafka module is incorporated in the release packages. The librdkafka dependency is statically linked in the build process now and there is no need for a separate install of librdkafka. 

So, with the current version 8.30.0 you can use
`apt-get install rsyslog rsyslog-kafka
`
and it should work alright.

This is only available on the stable ppa currently.

**Comment by saithejareddy** [comment]
`root@7791d18cfee7:/# apt-get install rsyslog-kafka
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rsyslog-kafka
`
I am not able install the rsyslog-kafka package..
I tried installing rsyslog from source and librdkafka-dev package in ubuntu 16.04, After I ran `./configure --enable-omkafka`, make and make intall both are throwing some errors
