### ISSUE TITLE
No package for mmrm1stspace module

### ISSUE THREAD

**Issue by selivan** [rsyslog/rsyslog-pkg-ubuntu#54]
This useful module appeared 2 month ago: https://github.com/rsyslog/rsyslog/commit/01d449c07c7a57f08a9788cdfefcb62c4fd503ea

No package available yet :(

**Comment by davidelang** [comment]
I would not expect a separate package for this, separate packages are created 
when a module requires significant additional dependencies, not for every 
module.

David Lang

**Comment by selivan** [comment]
Then it may be right to have it included in rsyslog package. Now to use this module on Ubuntu you have to compile rsyslog yourself

**Comment by davidelang** [comment]
It looks like it at this point. The 8.24 ppa does not seem to include this 
module.

David Lang
k

**Comment by selivan** [comment]
I wanted to make a PR, but @friedl already included mmrm1space as separate package in e8e2bdbac82f28e58456ace099e9736c57c34474 and it is already in PPA. Thank you guys! :+1:
