### ISSUE TITLE
postrotate script no longer working with systemd

### ISSUE THREAD

**Issue by ealphonse** [rsyslog/rsyslog-pkg-ubuntu#56]
Hello,

In Ubuntu Xenial release from [adiscon repo]( http://ppa.launchpad.net/adiscon/v8-stable/ubuntu), rsyslog provides a [logrotate config file](https://github.com/rsyslog/rsyslog-pkg-ubuntu/blob/f19426551f442185dc17d230bafbeea3ba66471e/rsyslog/xenial/master/debian/rsyslog.logrotate) that relies on the `reload` command.

However,  since 15.04, systemd replaced upstart, which gives:
```
# reload rsyslog
reload: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
```

The result is that rsyslog does not follow rotating files. The error is not noticed because of the postrotate script:
```
        postrotate
                reload rsyslog >/dev/null 2>&1 || true
        endscript
```

This issue seems to have been discussed in length for a while (e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=626365) but I would say the problem now is that the script should rely exclusively on systemd.

It works for me with `/usr/sbin/service rsyslog rotate >/dev/null 2>&1`. Is there another way to do it, like `systemctl restart`? Could it be implemented in upcoming releases?

Thank you in advance,
Regards

**Comment by davidelang** [comment]
rsyslog looks for file rotations when it receives a HUP signal, so what needs to 
happen is kill -HUP <rsyslog pid>

how you make this happen with your distro is up to you. I generally do killall 
-HUP rsyslog or pkill -HUP rsyslog

service and systemctl are just more complicated ways of getting the job done 
(and a reload/restart will actually cause you to loose logs while the restart 
happens, so that's not really what you want to be doing)

David Lang

(gumble about systemd making simple things complicated grumble :-)

**Comment by ealphonse** [comment]
Thanks @davidelang you are right! rsyslog should use `pkill` in its postrotate script.

**Comment by davidelang** [comment]
note that these scripts are maintained by the distro, not by rsyslog

**Comment by ealphonse** [comment]
even in [adiscon repo]( http://ppa.launchpad.net/adiscon/v8-stable/ubuntu)?

**Comment by deoren** [comment]
I got bit by this as well, especially where errors were being thrown away. Currently the `/etc/logrotate.d/rsyslog` conf I am using has this script block in place of the old:

<pre>
    postrotate
        # The Upstart job reference used before does not work for Ubuntu 16.04
        # and the provided systemd unit file doesn't provide a reload option.
        invoke-rc.d rsyslog rotate > /dev/null
    endscript
</pre>

This closely matches what was used before, but now allows error output to be caught/handled by cron.

**Comment by deoren** [comment]
As an update to my previous comments, I ended up modifying the postrotate block to use the init.d script instead of `invoke-rc.d` for Ubuntu 14.04 _and_ 16.04 compatibility. Attempting to use this block on Ubuntu 14.04:

```
    postrotate
        invoke-rc.d rsyslog rotate > /dev/null
    endscript
```

results in this error:

```
initctl: invalid command: rotate
Try `initctl --help' for more information.
invoke-rc.d: initscript rsyslog, action "rotate" failed.
```

Using this block works for both:

```
    postrotate
        /etc/init.d/rsyslog rotate > /dev/null
    endscript
```

**Comment by friedl** [comment]
Postrotate changed accordingly for Trusty, Xenial, Zesty and Artful

https://github.com/rsyslog/rsyslog-pkg-ubuntu/commit/30d580842cf09e982317e608abac1268a64507d4

**Comment by deoren** [comment]
@friedl Please see my notes on rsyslog/rsyslog#1506 re problems with the Ubuntu 14.04 package. The changes in 30d5808 fix logrotate issues for Ubuntu systems using systemd, but appears to not work for Ubuntu 14.04 LTS systems.
