### ISSUE TITLE
Logrotate on Ubuntu 16.04 fails

### ISSUE THREAD

**Issue by pjusur** [rsyslog/rsyslog-pkg-ubuntu#65]
Seems that the logrotate from [Logrotate](https://github.com/rsyslog/rsyslog-pkg-ubuntu/blob/master/rsyslog/xenial/v8-stable/debian/rsyslog.logrotate) fails because "reload" does not exists if upstart is not installed. Seems changing "reload rsyslog >/dev/null 2>&1 || true" to "invoke-rc.d rsyslog rotate > /dev/null" which is used by Ubuntus default rsyslog logrotate solves the problem.

**Comment by deoren** [comment]
Note: This appears to be a duplicate of #56.

**Comment by pjusur** [comment]
You are absolutely right, my bad should have seen it. Closing this one.
