### ISSUE TITLE
rsyslog : Depends: liblogging-stdlog1 but it is not installable (Ubuntu 17.10)

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog-pkg-ubuntu#73]
@friedl 

I ran:

1. `apt-add-repository ppa:adiscon/v8-stable`
1. `apt-get update`
1. `apt-get install rsyslog`

and got this error:

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  rsyslog : Depends: liblogging-stdlog1 but it is not installable
> E: Unable to correct problems, you have held broken packages.

This was on a new Ubuntu 17.10 installation. 

I checked the PPA site and found that there were 8 total packages for Xenial, but only 4 for Artful (which did not include the `liblogging-stdlog1` package.

Links:

- [PPA packages for Xenial](https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable?field.series_filter=xenial): 8 packages
- [PPA packages for Artful](https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable?field.series_filter=artful) : 4 packages

Screenshots are attached.
![adiscon_ubuntu_ppa_package_list_artful_2018-01-16](https://user-images.githubusercontent.com/1550338/35469013-5a0b34ce-02f1-11e8-8d61-6d938a336190.png)
![adiscon_ubuntu_ppa_package_list_xenial_2018-01-16](https://user-images.githubusercontent.com/1550338/35469014-5a19318c-02f1-11e8-9108-1c29f2d3bb84.png)

Please let me know if you need more info.

**Comment by deoren** [comment]
Hey guys,

I completely forgot that I submitted this ticket already and went to install rsyslog 8.33.0 on a test Ubuntu 17.10 VM to perform some testing. After checking, only four packages are available for Ubuntu 17.10, just as it was when I originally opened this.

I'll attempt to work around the problem by performing the testing within a Docker container, but I wanted to bump this ticket just in case this had fallen through with everything else going on.

**Comment by PepPepet** [comment]
Hi!

Same problem here.

Ubuntu 18.10 cosmic
4.18.0-14-lowlatency

trying to solve these errors found on syslog

`Feb  7 09:45:42 segarra rsyslogd: action 'action 4' suspended (module 'builtin:omfile'), retry 0. There should be messages before this one giving the reason for suspension. [v8.32.0 try http://www.rsyslog.com/e/2007 ]

Feb  7 09:45:42 segarra rsyslogd: action 'action 4' resumed (module 'builtin:omfile') [v8.32.0 try http://www.rsyslog.com/e/2359 ]

Feb  7 09:45:42 segarra rsyslogd: action 'action 4' suspended (module 'builtin:omfile'), retry 0. There should be messages before this one giving the reason for suspension. [v8.32.0 try http://www.rsyslog.com/e/2007 ]

Feb  7 09:45:42 segarra rsyslogd: action 'action 4' suspended (module 'builtin:omfile'), next retry is Thu 

Feb  7 09:46:12 2019, retry nbr 0. There should be messages before this one giving the reason for suspension. [v8.32.0 try http://www.rsyslog.com/e/2007 ]
`

Any solution?

Thanks in advance!

**Comment by rgerhards** [comment]
I am puzzled - is it indeed the same problem? Why do you think? It looks totally disconnected to me.

**Comment by PepPepet** [comment]
I did not expressed correctly, escuse me. I wanna meant that trying to fix the problems mentioned above, found the same when try to update rsyslog:

'The following packages have unmet dependencies:
 rsyslog : Depends: liblogging-stdlog1 but it is not installable
E: Unable to correct problems, you have held broken packages.'

Thanks again!

**Comment by rgerhards** [comment]
Ah, OK I see. I have submitted a PR and hope that @friedl will finally merge them today (and fix them up, probably ;-)).

**Comment by rgerhards** [comment]
lol.... tomorrow I meant (today is basically over over here ;-))

**Comment by friedl** [comment]
The packages have been rebuilt without the liblogging-stdlog dependency and are available for installation.

**Comment by PepPepet** [comment]
> The packages have been rebuilt without the liblogging-stdlog dependency and are available for installation.

Thank you so much friedl!
