### ISSUE TITLE
rsyslog 0.28.0 core dumps on ubuntu 16.10

### ISSUE THREAD

**Issue by glenp42** [rsyslog/rsyslog-pkg-ubuntu#75]
Hi,

I'm getting continual core dumps on my rsyslog 8.28 on my ubuntu 16.10 host.

If I run in rsyslogd -nd mode, I don't get any core dumps.

Log-wise, the only information I have is:
Mar  1 12:46:20 cacti kernel: [ 8038.001371] rs:writeRemoteD[30640]: segfault at 10 ip 000055b02e059a00 sp 00007f58b6a6cb70 error 4 in rsyslogd[55b02dff9000+97000]
Mar  1 12:46:20 cacti rsyslogd: warning: ~ action is deprecated, consider using the 'stop' statement instead [v8.28.0 try http://www.rsyslog.com/e/2307 ]
Mar  1 12:46:20 cacti rsyslogd:  message repeated 19 times: [warning: ~ action is deprecated, consider using the 'stop' statement instead [v8.28.0 try http://www.rsyslog.com/e/2307 ]]
Mar  1 12:46:20 cacti rsyslogd: rsyslogd's groupid changed to 108
Mar  1 12:46:20 cacti rsyslogd: rsyslogd's userid changed to 104
Mar  1 12:46:20 cacti rsyslogd:  [origin software="rsyslogd" swVersion="8.28.0" x-pid="6024" x-info="http://www.rsyslog.com"] start

Any ideas?

**Comment by glenp42** [comment]
Correction -- I do get the segfaults, it just takes a far longer time.

**Comment by rgerhards** [comment]
I guess this is fixed in the meantime (and should have been reported to the main rsyslog project, I didn't see it until today...)
