### ISSUE TITLE
rsyslog-redis - broken depends?

### ISSUE THREAD

**Issue by actionbuddha** [rsyslog/rsyslog-pkg-ubuntu#76]
The dependencies for rsyslog-redis 8.33 (and 8.32) in the repository appear to be broken:

`Package: rsyslog-redis`
`Version: 8.33.0-0adiscon1xenial1`
`Depends: libc6 (>= 2.4), libhiredis0.13 (>= 0.13.1), rsyslog (= 8.33.0-0adiscon1xenial1), libhiredis0.10`

This package will not install on my system due to the conflicting libhiredis requirements. By stripping the package apart and editing the control file to remove libhiredis0.10, the new package installs (and works) on my Ubuntu 16.04 system:

Depends: libc6 (>= 2.4), libhiredis0.13 (>= 0.13.1), rsyslog (= 8.33.0-0adiscon3xenial1)

**Comment by jharley** [comment]
I just opened #77 which should fix this (it was my fault to begin with -- apologies)

**Comment by jharley** [comment]
@actionbuddha I just confirmed that @friedl's new build after #77 was merged fixed this issue:

```
# apt-cache show rsyslog-redis
Package: rsyslog-redis
Source: rsyslog
Priority: extra
Section: admin
Installed-Size: 28
Maintainer: Andre Lorbach <alorbach@adiscon.com>
Architecture: amd64
Version: 8.33.1-0adiscon4xenial1
Depends: libc6 (>= 2.4), libhiredis0.13 (>= 0.13.1), rsyslog (= 8.33.1-0adiscon4xenial1)
Filename: pool/main/r/rsyslog/rsyslog-redis_8.33.1-0adiscon4xenial1_amd64.deb
Size: 8482
MD5sum: 44efa95c41d7327dff8f6c20d0732f81
SHA1: 545889fd564c93c93dfc1f34ad9ff4d074ef8b40
SHA256: 0086db8a51c8192399969db1e7ce9dc3d73b766ef7b6cc2ee9c9eeaab16eefdb
Description: This module implements Redis support, permitting ryslog to write to redis.
Description-md5: f55e06d7b07c8f31cd9bb4ac9f0f4dfc
Original-Vcs-Git: git://git.debian.org/git/collab-maint/rsyslog.git
Original-Vcs-Browser: http://git.debian.org/?p=collab-maint/rsyslog.git;a=summary
Original-Maintainer: Michael Biebl <biebl@debian.org>
```

**Comment by actionbuddha** [comment]
Looks perfect - confirmed I can now install rsyslog-redis with no issues. Thanks for the prompt turnaround!
