### ISSUE TITLE
Purging PPA of older versions with release is causing issues

### ISSUE THREAD

**Issue by jharley** [rsyslog/rsyslog-pkg-ubuntu#78]
Hello --

The practise of "unpublishing" the previous releases from the Launchpad PPA manifest has been causing us some grief with our deployments.. we pin rsyslog in scripts as we rely on features of the PPA version in our infrastructure, and want to ensure our versions are consistent across all environments for our own sanity.

For example, the release of 8.34.0 today has caused deployments to fail as 8.33.1 seems to be no longer published in the manifest (though, I do see the files [here](http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/pool/main/r/rsyslog/)).

Is there a reason to remove the previous versions from the manifest?  I'm happy to go the route of setting up a mirror if there is a reason for it, it's just making our upgrade path a bit bumpy and I'm sure I'm not the only one? :)

**Comment by rgerhards** [comment]
The reason is very simple: launchpad does this, not we 😉

**Comment by rgerhards** [comment]
I should add the we don't like it either...

**Comment by jharley** [comment]
Well.. that's no fun.  Thanks for the quick response.  I'll get things pulled into a more stable mirror for our purposes

**Comment by davidelang** [comment]
On Tue, 3 Apr 2018, Jason Harley wrote:

> Well.. that's no fun.  Thanks for the quick response.  I'll get things pulled into a more stable mirror for our purposes

As a general rule, you should pull from the Internet to an internal repo and 
then publish from there to your systems anyway. It's the only way to make sure 
that you can recreate a box exactly.

'pull the latest from the Internet and start running it' is a horrible practice.
