### ISSUE TITLE
install specific rsyslog package?

### ISSUE THREAD

**Issue by nanocosmos-ol** [rsyslog/rsyslog-pkg-ubuntu#85]
We had several issues with rsyslog and imfile in the past and would like to force a specific version to be installed based on the ubuntu repo, like 8.39, which does not seem to be available anymore.
Is it possible to force a specific version installation on ubuntu like 
apt install rsyslog=8.39
?

**Comment by rgerhards** [comment]
That's actually a question for canonical/ubuntu. To the best of my knowledge, this is not possible with the PPA system, as Ubuntu automatically removes all but the current version. Work-around is to create a local mirror. 

A better solution would be great, so let us know if you find one.

side-note: we experimentally have begun to build with SuSe OBS, I guess they don't have this issue.

**Comment by davidelang** [comment]
I would always suggest mirroring the repo to a local system and then installing 
all your systems from this internal mirror. That way you can always have your 
own images

take a look at aptly as a tool to help you do this.

David Lang
k

**Comment by rgerhards** [comment]
If you use the new OBS repository (see rsyslog homepage for repo links, as they may change over time), one should be able to obtain older versions.
