### ISSUE TITLE
Rsyslog omlibdbi module not there

### ISSUE THREAD

**Issue by Phatkone** [rsyslog/rsyslog-pkg-ubuntu#86]
Have tried many different versions and variations, cannot seem to get omlibdbi to work with rsyslog, I see the parent source has a module for it but it doesn't create the omlibdbi.so then it installs.

Ubuntu 18.04

**Comment by rgerhards** [comment]
Seen this via a search, but even though it's late like to add that omlibdbi is now available via the OBS repository specified on the rsyslog home page.
