### ISSUE TITLE
Build and publish the `omhttp` module in adiscon ppa

### ISSUE THREAD

**Issue by nbrownus** [rsyslog/rsyslog-pkg-ubuntu#89]
Looking to use the `omhttp` module, would be awesome if the ppa supplied it instead of having to build it by hand for each new release. Thanks!

**Comment by jgerhards** [comment]
There are experimental packages, most of which also include the omhttp module. You can find them [here](https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog).

**Comment by mbonsack** [comment]
But omhttp is now in master, correct?

**Comment by jgerhards** [comment]
Not everything is available as a package. Regarding omhttp/omhttpfs: This is because of dependencies for these modules.

More info at:
http://jan.gerhards.net/2019/03/rsyslog-packages-on-obs.html

**Comment by jgerhards** [comment]
Also direct link to repository:

https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

**Comment by mbonsack** [comment]
I followed this link, typed in "omhttp" in the search bar, and got nothing for omhttp.  _omhttfs_ shows up, but no omhttp.  So what steps, specifically, must the OP take to obtain an rsyslog binary that contains omhttp()?

**Comment by jgerhards** [comment]
Please see https://github.com/rsyslog/rsyslog/issues/3534#issuecomment-475968920
direct all discussion to that thread.

**Comment by sahya** [comment]
what state of this proposal? I think this  proposal is very nice.

**Comment by rgerhards** [comment]
Please see rsyslog/rsyslog#3534 (comment)
