### ISSUE TITLE
Can't Load IMRELP on Ubuntu 18.04 on Google Cloud

### ISSUE THREAD

**Issue by kaizen1** [rsyslog/rsyslog-pkg-ubuntu#92]
I'm running 18.04 Ubuntu. 
I try loading imrelp module, but the library is not installed. Is this Ubuntu or Google's bug with their mirror? Thanks.

syslogd: version 8.32.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: could not load module '/usr/lib/x86_64-linux-gnu/rsyslog/imrelp.so', dlopen: /usr/lib/x86_64-linux-gnu/rsyslog/imrelp.so: cannot open shared object file: No such file or directory  [v8.32.0 try http://www.rsyslog.com/e/2066 ]
rsyslogd: input module name 'imrelp' is unknown [v8.32.0 try http://www.rsyslog.com/e/2209 ]

**sudo apt-cache-policy**

rsyslog:
  Installed: 8.32.0-1ubuntu4
  Candidate: 8.32.0-1ubuntu4
  Version table:
 *** 8.32.0-1ubuntu4 500
        500 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by friedl** [comment]
Did you install the `rsyslog-relp` package?

**Comment by kaizen1** [comment]
Yes. I did. It's running fine now. Just thought it was strange not to be included by Ubuntu.
