### ISSUE TITLE
rsyslog-pgsql is not well behaved as a package

### ISSUE THREAD

**Issue by onet-git** [rsyslog/rsyslog-pkg-ubuntu#96]
Version: 8.2001.0-0adiscon1xenial1

There are two main issues with this package:

1) It has an interactive UI to configure a local pgsql instance as part of the package config step. In dpkg config steps are not skippable and are only supposed to include steps required for the package to function correctly. Configuration of the optional local pgsql server should instead be a postinst step, which you can tell dpkg to automatically skip.

2) This package drops a pgsql.conf file with an active configuration into /etc/rsyslog.d. Moreover the package restart rsyslog as part of postinst, automatically enabling a change in rsyslog behavior based on simply installing the package. The is contrary to the behavior to other rsyslog plugin packages, which only drop example configuration files (e.g. all directives commented out) into /etc/rsyslog.d.

The impact of this bug is that installing this package on systems where you don't want to run a local pgsql instance is quite troublesome and requires cleanup after install. Think specifically of a docker container that aggregates rsyslog messages and writes them to a pgsql instance running in the cloud. All you really want is the /usr/lib/rsyslog/ompgsql.so, but instead of simply installing the package you have pass the correct flags to dpkg to force a non-interactive install then cleanup after the install.

**Comment by onet-git** [comment]
The above summary is slightly inaccurate as you also do some configuration in postinst and postinst is also not bypassable.

My recommendation is to check DEBIAN_FRONTEND and not do those configuration steps if it is set to noninteractive.

The workaround that I have found is:
```
apt-get download rsyslog-pgsql
dpkg --unpack rsyslog-pgsql*.deb
```

That leaves the package unconfigured, which would be bad on a normal system but is fine in a docker container.

**Comment by rgerhards** [comment]
@friedl The question is if we need to install local pgsql server or leave that to the user. Probably that's the better idea?

**Comment by rgerhards** [comment]
I checked myself.

@onet-git We provide these packages as drop-in replacement for the distro version, "just" with newer release version. I experience the same thing like you do, but it is exactly how the native Ubuntu package works. As such, we cannot "fix" this here. I suggest you open an issue directly with Ubuntu. When they change the behavior, we will clone this change. But as of now, we cannot change anything, as this would remove the drop-in capability.
